# UI界面，暂未开发
# from proj_manga.mod_imports import *
#
# class Ui_Dialog(object):
#     def setupUi(self, Dialog):
#         Dialog.setObjectName("Dialog")
#         Dialog.resize(520, 355)
#         self.label = QtWidgets.QLabel(Dialog)
#         self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
#         self.label.setObjectName("label")
#         self.comboBox = QtWidgets.QComboBox(Dialog)
#         self.comboBox.setGeometry(QtCore.QRect(70, 320, 141, 22))
#         self.comboBox.setObjectName("comboBox")
#         self.pushButton = QtWidgets.QPushButton(Dialog)
#         self.pushButton.setGeometry(QtCore.QRect(200, 50, 71, 21))
#         self.pushButton.setObjectName("pushButton")
#         self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
#         self.textEdit_2.setGeometry(QtCore.QRect(280, 20, 221, 281))
#         self.textEdit_2.setObjectName("textEdit_2")
#         self.lineEdit = QtWidgets.QLineEdit(Dialog)
#         self.lineEdit.setGeometry(QtCore.QRect(10, 49, 181, 21))
#         self.lineEdit.setObjectName("lineEdit")
#         self.listView = QtWidgets.QListView(Dialog)
#         self.listView.setGeometry(QtCore.QRect(10, 80, 261, 171))
#         self.listView.setObjectName("listView")
#         self.label_2 = QtWidgets.QLabel(Dialog)
#         self.label_2.setGeometry(QtCore.QRect(10, 265, 54, 12))
#         self.label_2.setObjectName("label_2")
#         self.progressBar = QtWidgets.QProgressBar(Dialog)
#         self.progressBar.setGeometry(QtCore.QRect(280, 320, 221, 20))
#         self.progressBar.setProperty("value", 24)
#         self.progressBar.setObjectName("progressBar")
#         self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
#         self.lineEdit_2.setGeometry(QtCore.QRect(70, 260, 141, 20))
#         self.lineEdit_2.setObjectName("lineEdit_2")
#         self.pushButton_2 = QtWidgets.QPushButton(Dialog)
#         self.pushButton_2.setGeometry(QtCore.QRect(220, 260, 51, 23))
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.label_3 = QtWidgets.QLabel(Dialog)
#         self.label_3.setGeometry(QtCore.QRect(10, 293, 31, 16))
#         self.label_3.setObjectName("label_3")
#         self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
#         self.lineEdit_3.setGeometry(QtCore.QRect(40, 290, 51, 20))
#         self.lineEdit_3.setObjectName("lineEdit_3")
#         self.label_4 = QtWidgets.QLabel(Dialog)
#         self.label_4.setGeometry(QtCore.QRect(100, 291, 41, 16))
#         self.label_4.setObjectName("label_4")
#         self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
#         self.lineEdit_4.setGeometry(QtCore.QRect(140, 290, 51, 20))
#         self.lineEdit_4.setObjectName("lineEdit_4")
#         self.label_5 = QtWidgets.QLabel(Dialog)
#         self.label_5.setGeometry(QtCore.QRect(200, 292, 41, 16))
#         self.label_5.setObjectName("label_5")
#         self.pushButton_3 = QtWidgets.QPushButton(Dialog)
#         self.pushButton_3.setGeometry(QtCore.QRect(220, 320, 51, 23))
#         self.pushButton_3.setObjectName("pushButton_3")
#         self.label_6 = QtWidgets.QLabel(Dialog)
#         self.label_6.setGeometry(QtCore.QRect(10, 323, 71, 16))
#         self.label_6.setObjectName("label_6")
#         self.comboBox_2 = QtWidgets.QComboBox(Dialog)
#         self.comboBox_2.setGeometry(QtCore.QRect(90, 15, 141, 22))
#         self.comboBox_2.setObjectName("comboBox_2")
#
#         self.retranslateUi(Dialog)
#         QtCore.QMetaObject.connectSlotsByName(Dialog)
#
#         Dialog.show()
#
#     def retranslateUi(self, Dialog):
#         _translate = QtCore.QCoreApplication.translate
#         Dialog.setWindowTitle(_translate("Manga Helper v0.1 Beta", "漫画下载助手 v0.1 Beta"))
#         self.label.setText(_translate("Current Searching Engine", "当前搜索引擎"))
#         self.pushButton.setText(_translate("Search", "搜索"))
#         self.label_2.setText(_translate("Manga URL", "漫画地址"))
#         self.pushButton_2.setText(_translate("Check", "检查"))
#         self.label_3.setText(_translate("From", "从第"))
#         self.label_4.setText(_translate("Chapter to", "章至第"))
#         self.label_5.setText(_translate("Chapter", "章"))
#         self.pushButton_3.setText(_translate("Download", "下载"))
#         self.label_6.setText(_translate("File Extension", "文件格式"))
#
#
# if __name__ == "__main__":
#     app = QApplication(sys.argv)
#     form = QWidget()
#     w = Ui_Dialog()
#     w.setupUi(form)
#     form.show()
#     sys.exit(app.exec_())
